# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of InfluxDB systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ influxdb_identifier }}.service"
  register: influxdb_service_stat

- name: Uninstall InfluxDB systemd services and files
  when: influxdb_service_stat.stat.exists | bool
  block:
    - name: Ensure InfluxDB systemd service is stopped
      ansible.builtin.service:
        name: "{{ influxdb_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure InfluxDB systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ influxdb_identifier }}.service"
        state: absent

    - name: Ensure InfluxDB path does not exist
      ansible.builtin.file:
        path: "{{ influxdb_base_path }}"
        state: absent
